#Onboard data from the tello drone

#Pitch in degrees
int16 pitch

#Roll in degrees
int16 roll

#Yaw in degrees
int16 yaw

#X-axis speed m/s
float32 speed_x

#Y-axis speed m/s
float32 speed_y

#Z-axis speed m/s
float32 speed_z

#Acceleration of the “x” axis
float32 acceleration_x

#Acceleration of the “y” axis
float32 acceleration_y

#Acceleration of the “z” axis
float32 acceleration_z

#Relative height in m
float32 rel_height

#Absolute height in m based on barometer
float32 abs_height

#TOF height based on IR camera
float32 tof_height

#Percentage of battery
int16 battery