#Onboard data from the tello drone

#Pitch in degrees
int16 pitch

#Roll in degrees
int16 roll

#Yaw in degrees
int16 yaw

#X-axis speed
int16 speed_x

#Y-axis speed
int16 speed_y

#Z-axis speed
int16 speed_z

#Acceleration of the “x” axis
float32 acceleration_x

#Acceleration of the “y” axis
float32 acceleration_y

#Acceleration of the “z” axis
float32 acceleration_z

#Relative height in cm
int32 rel_height

#Absolute height in cm based on barometer
int32 abs_height

#Percentage of battery
int16 battery